### ISSUE TITLE
NPE in shortdoi match

### ISSUE THREAD

**Issue by afandian** [CrossRef/event-data-percolator#53]
```
Exception in thread "async-thread-macro-7" [main] WARN event-data-percolator.process - One thread died, exiting.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  at java.lang.String.substring(String.java:1931)
  at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
  at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
  at event_data_percolator.matchers.shortdoi_url$match_shortdoi_url.invokeStatic(shortdoi_url.clj:10)
  at event_data_percolator.matchers.shortdoi_url$match_shortdoi_url.invoke(shortdoi_url.clj:6)
  at event_data_percolator.matchers.shortdoi_url$match_shortdoi_url_candidate.invokeStatic(shortdoi_url.clj:18)
  at event_data_percolator.matchers.shortdoi_url$match_shortdoi_url_candidate.invoke(shortdoi_url.clj:15)
  at event_data_percolator.match$match_candidate.invokeStatic(match.clj:30)
  at event_data_percolator.match$match_candidate.invoke(match.clj:27)
  at event_data_percolator.action$match_candidates$fn__12764$fn__12765.invoke(action.clj:62)
  at clojure.core$map$fn__4785.invoke(core.clj:2646)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.core$seq__4357.invokeStatic(core.clj:137)
  at clojure.core$filter$fn__4812.invoke(core.clj:2700)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:56)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.core$seq__4357.invokeStatic(core.clj:137)
  at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
  at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
  at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
  at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
  at clojure.core$reduce.invokeStatic(core.clj:6545)
  at clojure.core$group_by.invokeStatic(core.clj:6860)
  at clojure.core$group_by.invoke(core.clj:6860)
  at event_data_percolator.action$dedupe_matches.invokeStatic(action.clj:93)
  at event_data_percolator.action$dedupe_matches.invoke(action.clj:86)
  at clojure.core$map$fn__4785.invoke(core.clj:2644)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.core$seq__4357.invokeStatic(core.clj:137)
  at clojure.core$map$fn__4785.invoke(core.clj:2637)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.core$seq__4357.invokeStatic(core.clj:137)
  at clojure.core$map$fn__4785.invoke(core.clj:2637)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
  at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
  at clojure.lang.RT.next(RT.java:688)
  at clojure.core$next__4341.invokeStatic(core.clj:64)
  at clojure.core$dorun.invokeStatic(core.clj:3033)
  at clojure.core$doall.invokeStatic(core.clj:3039)
  at clojure.walk$walk.invokeStatic(walk.clj:46)
  at clojure.walk$postwalk.invokeStatic(walk.clj:52)
  at clojure.walk$postwalk.invoke(walk.clj:52)
  at clojure.core$partial$fn__4759.invoke(core.clj:2515)
  at clojure.core$map$fn__4785.invoke(core.clj:2644)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
  at clojure.core$vec.invokeStatic(core.clj:377)
  at clojure.walk$walk.invokeStatic(walk.clj:45)
  at clojure.walk$postwalk.invokeStatic(walk.clj:52)
  at clojure.walk$postwalk.invoke(walk.clj:52)
  at clojure.core$partial$fn__4759.invoke(core.clj:2515)
  at clojure.core$map$fn__4785.invoke(core.clj:2646)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.core$seq__4357.invokeStatic(core.clj:137)
  at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
  at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
  at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
  at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
  at clojure.core$reduce.invokeStatic(core.clj:6545)
  at clojure.core$into.invokeStatic(core.clj:6610)
  at clojure.walk$walk.invokeStatic(walk.clj:49)
  at clojure.walk$postwalk.invokeStatic(walk.clj:52)
  at clojure.walk$postwalk.invoke(walk.clj:52)
  at clojure.core$partial$fn__4759.invoke(core.clj:2515)
  at clojure.core$map$fn__4785.invoke(core.clj:2644)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.core$seq__4357.invokeStatic(core.clj:137)
  at clojure.core$dorun.invokeStatic(core.clj:3024)
  at clojure.core$doall.invokeStatic(core.clj:3039)
  at clojure.walk$walk.invokeStatic(walk.clj:46)
  at clojure.walk$postwalk.invokeStatic(walk.clj:52)
  at clojure.walk$postwalk.invoke(walk.clj:52)
  at clojure.core$partial$fn__4759.invoke(core.clj:2515)
  at clojure.core$map$fn__4785.invoke(core.clj:2644)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
  at clojure.core$vec.invokeStatic(core.clj:377)
  at clojure.walk$walk.invokeStatic(walk.clj:45)
  at clojure.walk$postwalk.invokeStatic(walk.clj:52)
  at clojure.walk$postwalk.invoke(walk.clj:52)
  at clojure.core$partial$fn__4759.invoke(core.clj:2515)
  at clojure.core$map$fn__4785.invoke(core.clj:2646)
  at clojure.lang.LazySeq.sval(LazySeq.java:40)
  at clojure.lang.LazySeq.seq(LazySeq.java:49)
  at clojure.lang.RT.seq(RT.java:521)
  at clojure.core$seq__4357.invokeStatic(core.clj:137)
  at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
  at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
  at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
  at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
  at clojure.core$reduce.invokeStatic(core.clj:6545)
  at clojure.core$into.invokeStatic(core.clj:6610)
  at clojure.walk$walk.invokeStatic(walk.clj:49)
  at clojure.walk$postwalk.invokeStatic(walk.clj:52)
  at clojure.walk$postwalk.invoke(walk.clj:52)
  at event_data_percolator.input_bundle$process.invokeStatic(input_bundle.clj:143)
  at event_data_percolator.input_bundle$process.invoke(input_bundle.clj:125)
  at event_data_percolator.process$process_input_bundle.invokeStatic(process.clj:60)
  at event_data_percolator.process$process_input_bundle.invoke(process.clj:53)
  at event_data_percolator.process$process_input_bundle_and_enqueue.invokeStatic(process.clj:64)
  at event_data_percolator.process$process_input_bundle_and_enqueue.invoke(process.clj:62)
  at event_data_common.queue$process_queue.invokeStatic(queue.clj:58)
  at event_data_common.queue$process_queue.invoke(queue.clj:46)
  at event_data_percolator.process$run_process$fn__15506$fn__15507.invoke(process.clj:76)
  at clojure.core.async$thread_call$fn__7106.invoke(async.clj:439)
  at clojure.lang.AFn.run(AFn.java:22)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by afandian** [comment]
Duplicate of #40 already fixed.
